---
title: "Netflix Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library("dplyr")
library("ggplot2")
library("ggrepel")
library("DT")
library("tidyr")
library("forcats")
df_netflix <- read.csv("finalMergedNetflixData.csv")
df_netflix$date_added <- as.Date(df_netflix$date_added, format = "%d-%B-%Y")
```

Page 1
=====================================  

Column {data-Width=500}
-----------------------------------------------------------------------

### Table showing processed data

```{r}
datatable(df_netflix, height = 500)
```

Column {data-width=500}
-----------------------------------------------------------------------

### pie chart of movies and tv shows
```{r}
ratio=table(as.matrix(df_netflix$type))
pie(ratio, main = "Movies and TV shows",col = rainbow(length(ratio)))
legend("topright", c("Movies","TV Shows"),
   fill = rainbow(length(ratio)))

```

Page 2
=====================================

Column {data-width=500}
-----------------------------------------------------------------------
### stacked bar chart representation of shows and movies over the years

```{r}
ggplot(df_netflix, aes(fill=type, x=release_year)) + 
    geom_bar(position="stack", stat="bin", color = "black", binwidth = 1)

```


### Show Categories: Correlations and most frequent

``` {r}
df_show_categories <- df_netflix %>% 
                        select(c('show_id','type','listed_in')) %>% 
                        separate_rows(listed_in, sep = ',') %>%
                        rename(Show_Category = listed_in)
df_show_categories$Show_Category <- trimws(df_show_categories$Show_Category)
df_show_categories %>% mutate(Show_Category = fct_infreq(Show_Category)) %>% 
        ggplot(aes(x = Show_Category)) + 
            geom_bar(color = "#F8766D", fill = "#F8766D") + scale_x_discrete() + facet_wrap(~type, scales = 'free_x') + coord_cartesian(xlim = c(1,20)) + theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
```

Column {data-width=500}
-----------------------------------------------------------------------
### line chart of number of releases per year

```{r}

df_by_date <- df_netflix %>% group_by(release_year,type) %>% summarise(addedToday = n()) %>% 
            ungroup() %>% group_by(type) %>% mutate(Total_Number_of_Shows = cumsum(addedToday), label = if_else(release_year == max(release_year,na.rm = T), as.character(type), NA_character_))


df_by_date  %>% 
                ggplot(aes(x = release_year, y = Total_Number_of_Shows, color = type)) + geom_line(size = 2) + 
                    theme_bw(base_size = 20) + 
                    theme(legend.position = 'none') +
                    labs(x="Release Year", y="Count", title=NULL)+
                    geom_text_repel(aes(label = label), size = 8,na.rm = TRUE, nudge_y = 100)

```

### Number of shows available in Netflix as a function of time
```{r}
df_by_date <- df_netflix %>% group_by(date_added,type) %>% summarise(addedToday = n()) %>% 
            ungroup() %>% group_by(type) %>% mutate(Total_Number_of_Shows = cumsum(addedToday), label = if_else(date_added == max(date_added,na.rm = T), as.character(type), NA_character_))


df_by_date  %>% 
                ggplot(aes(x = date_added, y = Total_Number_of_Shows, color = type)) + geom_line(size = 2) + 
                    theme_bw(base_size = 20) + 
                    scale_x_date(date_breaks = '2 years', date_labels = "%Y") + 
                    theme(legend.position = 'none') +
                    geom_text_repel(aes(label = label), size = 8,na.rm = TRUE, nudge_y = 100)

```

Page 3
===================================== 


Column {data-width=500}
-----------------------------------------------------------------------
### bar chart of ratings of shows region wise
```{r}
d <- transform(df_netflix, normRating = averageRating / numVotes *100)
d$normRating <- format(d$normRating, scientific = FALSE)
ggplot(d, aes(x = region, y = normRating, fill = region)) + 
  geom_bar(stat = "identity") +
  labs(x=NULL, y="normalised rating", title = NULL)+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```


### regression of rating vs release year
```{r}
mean <- df_netflix %>% group_by(release_year) %>% summarise(mean_val = mean(averageRating))
gg <- ggplot()
gg <- gg + geom_point(data=df_netflix,
                      aes(x=release_year, y=averageRating, color=type))
gg <- gg + labs(x="Release Year", y="average rating", title=NULL)
gg <- gg + stat_summary(fun.data=mean_cl_normal)
gg <- gg + geom_line(data= mean, aes(x = release_year, y = mean_val, group = 1))
gg <- gg + theme_bw()
gg
```

Column {data-width=500}
-----------------------------------------------------------------------

### Correlation of parental rating and avg rating
```{r}
mean <- df_netflix %>% group_by(rating) %>% summarise(mean_val = mean(averageRating))
gg <- ggplot()
gg <- gg + geom_point(data=df_netflix,
                      aes(x=rating, y=averageRating, color=type))
gg <- gg + labs(x="parental rating", y="average rating", title=NULL)
gg <- gg + geom_line(data= mean, aes(x = rating, y = mean_val, group = 1))
gg <- gg + theme_bw()
gg
```

### correlation of duration and avg rating
```{r}
movies <- subset(df_netflix, type == "Movie")
library(stringr)

d = movies$duration

na_to_0 = function(x) {x[is.na(x)] = 0; x}

to_minutes = function(s) {

  hr = na_to_0(60 *  as.numeric(str_replace(str_extract(s, "[0-9]{1,2} h"), " h", "")))
  min = na_to_0(as.numeric(str_replace(str_extract(s, "[0-9]{1,3} min"), " min", "")))

  hr + min
}

movies$duration <- to_minutes(d) 
gg <- ggplot(data=movies,
                      aes(x=duration, y=averageRating), col = "#F8766D")
gg <- gg + geom_line(stat = "summary", fun = "mean", color = "#F8766D")
gg <- gg + geom_smooth()
gg <- gg + labs(x="Duration", y="average rating", title=NULL)
gg
```